<?xml version="1.0"?>
<package format="3">
  <name>greenhouse_vision</name>
  <version>0.1.0</version>

  <description>
    YOLO11n NCNN person detector for greenhouse AMR.
  </description>

  <maintainer email="poom@todo.todo">poom</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>greenhouse_vision_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
