person_detector:
  ros__parameters:
    model_path: /home/poom/Desktop/Greenhouse-Logistics-AMR-ROS2/yolo11n_ncnn_model

    device: /dev/video0
    width: 640
    height: 480
    camera_fps: 30

    imgsz: 320
    confidence: 0.35
    target_fps: 10.0
    warmup_runs: 60

    # largest หรือ highest_confidence
    target_strategy: largest

    log_interval_sec: 2.0
